steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --progress-bar off --upgrade pip setuptools wheel
    python -m pip install --progress-bar off --force-reinstall tk
    python -m pip install --progress-bar off .[test]
  displayName: 'Install dependencies'

- script: |
    pytest pycrostates --junitxml=junit/test-results.xml --cov=pycrostates --cov-report=xml
  displayName: 'Run tests'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

- bash: |
     bash <(curl -s https://codecov.io/bash)
  condition: and(eq(variables['Agent.OS'], 'Linux' ), eq(variables['python.version'], '3.9' ))
  displayName: 'Upload to codecov.io'
